version: '3.8'
services:
  fhir:
    image: fhir
    build:
      context: ./fhir
      dockerfile: Dockerfile-dev
    volumes:
      - ./fhir/src:/usr/src/app/src
    ports:
      - 3000:3000
    environment:
      - TCGA_URL=http://tcga:3001
      - ANVIL_URL=http://anvil:3002
      - URL=http://localhost:3000/4_0_0

  tcga:
    image: tcga
    build:
      context: ./tcga
      dockerfile: Dockerfile-dev
    volumes:
      - ./tcga/src:/usr/src/app/src
    ports:
      - 3001:3001
    environment:
      - PORT=3001
  anvil-mongo:
    image: mongo
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=anvil-admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=anvil
      - ANVIL_READ_PASSWORD=${ANVIL_READ_PASSWORD}
      - ANVIL_RW_PASSWORD=${ANVIL_RW_PASSWORD}
      - PUID=1000
      - PGID=1000
    volumes:
      - ./anvil-mongodb/database:/data/db
      - ./anvil-mongodb/mongo-schema/:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017
    restart: unless-stopped

  anvil:
    image: anvil
    build:
      context: ./anvil-api
      dockerfile: Dockerfile-dev
    volumes:
      - ./anvil-api/src:/usr/src/app/src
    ports:
      - 3002:3002
    environment:
      - PORT=3002
      - MONGO_CONNECTION_STRING=${MONGO_READ_CONNECTION_STRING}
