version: "3.8"
services:
  anvil-mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=anvil-admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=anvil
      - PUID=1000
      - PGID=1000
    volumes:
      - ./anvil-mongodb/database:/data/db
      - ./anvil-mongodb/mongo-schema/:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017
    restart: unless-stopped