const workspaceFixture = {
  _id: '6035292a66518597ddf17246',
  name: 'AnVIL_CMG_Broad_Muscle_KNC_WES',
  lmsvn: 6,
  requiresExternalApproval: false,
  discoverableByGroups: [],
  dulvn: 4,
  studyDesign: 'NA',
  description:
    "Rare muscular disease samples submitted to the Broad Center for Mendelian Genomics by the Kids Neuroscience Centre of the Sydney Children's Hospitals Network. Cohort consists of WES samples aligned to hg38.",
  institute: ['Broad'],
  published: false,
  instrumentType: 'Illumina',
  studyPi: 'Nigel Clarke',
  indication: 'NA',
  contactEmail: 'help@lists.anvilproject.org',
  fileFormat: 'CRAM',
  numSubjects: 35,
  datasetOwner: 'NA',
  datatype: ['Exome'],
  datasetCustodian: 'larkin@broadinstitute.org',
  projectName: 'NA',
  libraryStrategy: 'WES',
  technology: ['Illumina'],
  genomeReferenceVersion: 'GRCh38/hg38',
  tags: [
    'Mendelian Rare Disease Exome v2',
    'RP-1113',
    'C1991',
    'PDO-11380',
    'PDO-8294',
    'Exome',
    'PDO-11379',
    'Mar 26, 2019',
    'CMG_Clarke',
    'GRCh38/hg38',
    'PDO-12329',
    'Access WS',
    'Mendelian Rare Disease Exome',
    'Standard Germline Exome v5',
  ],
  dataUseRestriction: 'NA',
  datasetDepositor: 'larkin@broadinstitute.org',
  studyAccession: 'phs001272.v1.p1.c4',
  studyConsents: '["DS-NIC-EMP-LENF"]',
  reference: 'GRCh38/hg38',
  datasetVersion: '1',
  datasetName: 'CMG_Broad_Muscle_KNC_WES',
  dataCategory: ['Raw Sequencing data'],
  primarySite: 'Muscle',
  dataFileFormats: ['CRAM'],
  useLimitationOption: 'skip',
  studyPhs: 'phs001272',
  datasetDescription: 'CMG_Broad_Muscle_KNC_WES',
};

const sampleFixture = {};

const subjectFixture = {};

module.exports = {
  workspaceFixture,
  sampleFixture,
  subjectFixture,
};
