---
apiVersion: v1
kind: Service
metadata:
  name: broad-anvil-svc
spec:
  selector:
    app: broad-anvil-deployment
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broad-anvil-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broad-anvil-deployment
  template:
    metadata:
      labels:
        app: broad-anvil-deployment
    spec:
      containers:
        - name: anvil
          image: gcr.io/broad-fhir-dev/broad/anvil:5f102a9
          ports:
            - containerPort: 3002
