apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fhir
  template:
    metadata:
      labels:
        app: fhir
    spec:
      containers:
        - name: fhir
          image: gcr.io/broad-fhir-dev/broad/fhir:2a641df
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
