const BigQuery = require('../services/BigQuery');

jest.mock('../services/BigQuery');

BigQuery.mockImplementation(() => ({
  get: () => [[{ message: 'test' }], 1],
}));

const service = require('./service');

describe('service tests', () => {
  it.todo('should getByID');
  it.todo('should transform results from TCGA');

  it('should getAll', async () => {
    const [rows] = await service.getAll();
    expect(rows).toEqual([
      {
        submitter_id: undefined,
        case_id: undefined,
        diag__treat__count: undefined,
        primary_site: undefined,
        disease_type: undefined,
        proj__name: undefined,
        proj__project_id: undefined,
        demo__demographic_id: undefined,
        demo__gender: undefined,
        demo__race: undefined,
        demo__ethnicity: undefined,
        demo__vital_status: undefined,
        demo__days_to_birth: undefined,
        demo__year_of_birth: undefined,
        demo__age_at_index: undefined,
        demo__year_of_death: undefined,
        demo__days_to_death: undefined,
        demo__state: undefined,
        demo__created_datetime: undefined,
        demo__updated_datetime: undefined,
        diag__diagnosis_id: undefined,
        diag__ajcc_clinical_n: undefined,
        diag__masaoka_stage: undefined,
        diag__ajcc_clinical_m: undefined,
        diag__primary_diagnosis: undefined,
        diag__primary_gleason_grade: undefined,
        diag__year_of_diagnosis: undefined,
        diag__figo_stage: undefined,
        diag__progression_or_recurrence: undefined,
        diag__ajcc_pathologic_m: undefined,
        diag__site_of_resection_or_biopsy: undefined,
        diag__ajcc_staging_system_edition: undefined,
        diag__icd_10_code: undefined,
        diag__age_at_diagnosis: undefined,
        diag__ajcc_clinical_t: undefined,
        diag__days_to_last_follow_up: undefined,
        diag__ajcc_pathologic_stage: undefined,
        diag__tumor_grade: undefined,
        diag__last_known_disease_status: undefined,
        diag__ann_arbor_extranodal_involvement: undefined,
        diag__ajcc_clinical_stage: undefined,
        diag__secondary_gleason_grade: undefined,
        diag__synchronous_malignancy: undefined,
        diag__morphology: undefined,
        diag__ajcc_pathologic_t: undefined,
        diag__igcccg_stage: undefined,
        diag__classification_of_tumor: undefined,
        diag__ann_arbor_clinical_stage: undefined,
        diag__ann_arbor_b_symptoms: undefined,
        diag__tumor_stage: undefined,
        diag__prior_treatment: undefined,
        diag__ajcc_pathologic_n: undefined,
        diag__tissue_or_organ_of_origin: undefined,
        diag__prior_malignancy: undefined,
        diag__state: undefined,
        diag__created_datetime: undefined,
        diag__updated_datetime: undefined,
        exp__exposure_id: undefined,
        exp__height: undefined,
        exp__weight: undefined,
        exp__bmi: undefined,
        exp__years_smoked: undefined,
        exp__pack_years_smoked: undefined,
        exp__cigarettes_per_day: undefined,
        exp__alcohol_history: undefined,
        exp__state: undefined,
        exp__created_datetime: undefined,
        exp__updated_datetime: undefined,
        state: undefined,
        updated_datetime: undefined,
        diagnoses: [
          {
            diag__diagnosis_id: undefined,
            diag__treat__treatment_id: undefined,
            case_id: undefined,
            diag__treat__treatment_type: undefined,
            diag__treat__treatment_or_therapy: undefined,
            diag__treat__state: undefined,
            diag__treat__created_datetime: undefined,
            diag__treat__updated_datetime: undefined,
          },
        ],
        biospecimen: [
          {
            sample_barcode: undefined,
            sample_gdc_id: undefined,
            case_barcode: undefined,
            case_gdc_id: undefined,
            sample_type: undefined,
            sample_type_name: undefined,
            program_name: undefined,
            project_short_name: undefined,
            batch_number: undefined,
            bcr: undefined,
            days_to_collection: undefined,
            days_to_sample_procurement: undefined,
            is_ffpe: undefined,
            num_portions: undefined,
            num_slides: undefined,
            avg_percent_lymphocyte_infiltration: undefined,
            avg_percent_monocyte_infiltration: undefined,
            avg_percent_necrosis: undefined,
            avg_percent_neutrophil_infiltration: undefined,
            avg_percent_normal_cells: undefined,
            avg_percent_tumor_nuclei: undefined,
            max_percent_lymphocyte_infiltration: undefined,
            max_percent_monocyte_infiltration: undefined,
            max_percent_necrosis: undefined,
            max_percent_neutrophil_infiltration: undefined,
            max_percent_normal_cells: undefined,
            max_percent_stromal_cells: undefined,
            max_percent_tumor_cells: undefined,
            max_percent_tumor_nuclei: undefined,
            min_percent_lymphocyte_infiltration: undefined,
            min_percent_monocyte_infiltration: undefined,
            min_percent_necrosis: undefined,
            min_percent_neutrophil_infiltration: undefined,
            min_percent_normal_cells: undefined,
            min_percent_stromal_cells: undefined,
            min_percent_tumor_cells: undefined,
            min_percent_tumor_nuclei: undefined,
          },
        ],
      },
    ]);
  });
});
