const tcgaResults = require('../../__fixtures__/tcga/tcgaresults.json');

const BigQuery = require('../services/BigQuery');

jest.mock('../services/BigQuery');

BigQuery.mockImplementation(() => ({
  get: () => [tcgaResults, 10],
}));

const service = require('./service');

describe('service tests', () => {
  it('should getByID', async () => {
    const rows = await service.getGdcById('foobar');
    expect(rows).toEqual({
      submitter_id: 'TCGA-CN-5363',
      case_id: '291b069c-9dde-4e1e-8430-85146bc94338',
      diag__treat__count: 2,
      primary_site: 'Larynx',
      disease_type: 'Squamous Cell Neoplasms',
      proj__name: 'Head and Neck Squamous Cell Carcinoma',
      proj__project_id: 'TCGA-HNSC',
      demo__demographic_id: '2611cb61-6d05-5286-b94a-ce6cac2ba37b',
      demo__gender: 'male',
      demo__race: 'black or african american',
      demo__ethnicity: 'not hispanic or latino',
      demo__vital_status: 'Dead',
      demo__days_to_birth: -17635,
      demo__year_of_birth: 1959,
      demo__age_at_index: 48,
      demo__year_of_death: 2007,
      demo__days_to_death: 253,
      demo__state: 'released',
      demo__created_datetime: null,
      demo__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
      diag__diagnosis_id: '4176108f-948d-5715-afbb-cc21f3cbfaf5',
      diag__ajcc_clinical_n: 'N3',
      diag__masaoka_stage: null,
      diag__ajcc_clinical_m: 'M0',
      diag__primary_diagnosis: 'Squamous cell carcinoma, NOS',
      diag__primary_gleason_grade: null,
      diag__year_of_diagnosis: 2007,
      diag__figo_stage: null,
      diag__progression_or_recurrence: 'not reported',
      diag__ajcc_pathologic_m: 'M0',
      diag__site_of_resection_or_biopsy: 'Larynx, NOS',
      diag__ajcc_staging_system_edition: '6th',
      diag__icd_10_code: 'C32.9',
      diag__age_at_diagnosis: 17635,
      diag__ajcc_clinical_t: 'T4a',
      diag__days_to_last_follow_up: null,
      diag__ajcc_pathologic_stage: 'Stage IVB',
      diag__tumor_grade: 'not reported',
      diag__last_known_disease_status: 'not reported',
      diag__ann_arbor_extranodal_involvement: null,
      diag__ajcc_clinical_stage: 'Stage IVB',
      diag__secondary_gleason_grade: null,
      diag__synchronous_malignancy: 'No',
      diag__morphology: '8070/3',
      diag__ajcc_pathologic_t: 'T4a',
      diag__igcccg_stage: null,
      diag__classification_of_tumor: 'not reported',
      diag__ann_arbor_clinical_stage: null,
      diag__ann_arbor_b_symptoms: null,
      diag__tumor_stage: 'stage ivb',
      diag__prior_treatment: 'No',
      diag__ajcc_pathologic_n: 'N3',
      diag__tissue_or_organ_of_origin: 'Larynx, NOS',
      diag__prior_malignancy: 'no',
      diag__state: 'released',
      diag__created_datetime: null,
      diag__updated_datetime: '2019-08-08T16:44:42.154844-05:00',
      exp__exposure_id: 'beef5b0a-0621-5abd-97bc-d0ef1261a94d',
      exp__height: null,
      exp__weight: null,
      exp__bmi: null,
      exp__years_smoked: null,
      exp__pack_years_smoked: 15,
      exp__cigarettes_per_day: 0.821917808219178,
      exp__alcohol_history: 'Yes',
      exp__state: 'released',
      exp__created_datetime: null,
      exp__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
      state: 'released',
      updated_datetime: '2019-08-06T14:25:25.511101-05:00',
      diagnoses: [
        {
          diag__diagnosis_id: '4176108f-948d-5715-afbb-cc21f3cbfaf5',
          diag__treat__treatment_id: 'e62a815e-6907-5bc7-acbc-932bc0a05b75',
          case_id: '291b069c-9dde-4e1e-8430-85146bc94338',
          diag__treat__treatment_type: 'Pharmaceutical Therapy, NOS',
          diag__treat__treatment_or_therapy: 'not reported',
          diag__treat__state: 'released',
          diag__treat__created_datetime: '2019-04-28T11:26:52.133657-05:00',
          diag__treat__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
        },
        {
          diag__diagnosis_id: '4176108f-948d-5715-afbb-cc21f3cbfaf5',
          diag__treat__treatment_id: 'f46facb0-9a93-5077-a9b5-b8f907404520',
          case_id: '291b069c-9dde-4e1e-8430-85146bc94338',
          diag__treat__treatment_type: 'Radiation Therapy, NOS',
          diag__treat__treatment_or_therapy: 'not reported',
          diag__treat__state: 'released',
          diag__treat__created_datetime: null,
          diag__treat__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
        },
      ],
      biospecimen: [
        {
          sample_barcode: 'TCGA-CN-5363-10A',
          sample_gdc_id: '591e99ec-46f9-442d-ac20-745dccc8a52b',
          case_barcode: 'TCGA-CN-5363',
          case_gdc_id: '291b069c-9dde-4e1e-8430-85146bc94338',
          sample_type: '10',
          sample_type_name: 'Blood Derived Normal',
          program_name: 'TCGA',
          project_short_name: 'TCGA-HNSC',
          batch_number: 54,
          bcr: "Nationwide Children's Hospital",
          days_to_collection: null,
          days_to_sample_procurement: 27,
          is_ffpe: 'NO',
          num_portions: 1,
          num_slides: 0,
          avg_percent_lymphocyte_infiltration: null,
          avg_percent_monocyte_infiltration: null,
          avg_percent_necrosis: null,
          avg_percent_neutrophil_infiltration: null,
          avg_percent_normal_cells: null,
          avg_percent_tumor_nuclei: null,
          max_percent_lymphocyte_infiltration: null,
          max_percent_monocyte_infiltration: null,
          max_percent_necrosis: null,
          max_percent_neutrophil_infiltration: null,
          max_percent_normal_cells: null,
          max_percent_stromal_cells: null,
          max_percent_tumor_cells: null,
          max_percent_tumor_nuclei: null,
          min_percent_lymphocyte_infiltration: null,
          min_percent_monocyte_infiltration: null,
          min_percent_necrosis: null,
          min_percent_neutrophil_infiltration: null,
          min_percent_normal_cells: null,
          min_percent_stromal_cells: null,
          min_percent_tumor_cells: null,
          min_percent_tumor_nuclei: null,
        },
        {
          sample_barcode: 'TCGA-CN-5363-01A',
          sample_gdc_id: '5e4e1e21-8016-4e27-8f72-2411714203e8',
          case_barcode: 'TCGA-CN-5363',
          case_gdc_id: '291b069c-9dde-4e1e-8430-85146bc94338',
          sample_type: '01',
          sample_type_name: 'Primary solid Tumor',
          program_name: 'TCGA',
          project_short_name: 'TCGA-HNSC',
          batch_number: 54,
          bcr: "Nationwide Children's Hospital",
          days_to_collection: null,
          days_to_sample_procurement: 3,
          is_ffpe: 'NO',
          num_portions: 1,
          num_slides: 2,
          avg_percent_lymphocyte_infiltration: null,
          avg_percent_monocyte_infiltration: null,
          avg_percent_necrosis: 0,
          avg_percent_neutrophil_infiltration: null,
          avg_percent_normal_cells: 0,
          avg_percent_tumor_nuclei: 70,
          max_percent_lymphocyte_infiltration: null,
          max_percent_monocyte_infiltration: null,
          max_percent_necrosis: null,
          max_percent_neutrophil_infiltration: null,
          max_percent_normal_cells: 0,
          max_percent_stromal_cells: 10,
          max_percent_tumor_cells: 90,
          max_percent_tumor_nuclei: 70,
          min_percent_lymphocyte_infiltration: null,
          min_percent_monocyte_infiltration: null,
          min_percent_necrosis: 0,
          min_percent_neutrophil_infiltration: null,
          min_percent_normal_cells: 0,
          min_percent_stromal_cells: 10,
          min_percent_tumor_cells: 90,
          min_percent_tumor_nuclei: 70,
        },
      ],
    });
  });

  it('should getAll', async () => {
    const [rows] = await service.getAllGdc();
    expect(rows).toEqual([
      {
        submitter_id: 'TCGA-CN-5363',
        case_id: '291b069c-9dde-4e1e-8430-85146bc94338',
        diag__treat__count: 2,
        primary_site: 'Larynx',
        disease_type: 'Squamous Cell Neoplasms',
        proj__name: 'Head and Neck Squamous Cell Carcinoma',
        proj__project_id: 'TCGA-HNSC',
        demo__demographic_id: '2611cb61-6d05-5286-b94a-ce6cac2ba37b',
        demo__gender: 'male',
        demo__race: 'black or african american',
        demo__ethnicity: 'not hispanic or latino',
        demo__vital_status: 'Dead',
        demo__days_to_birth: -17635,
        demo__year_of_birth: 1959,
        demo__age_at_index: 48,
        demo__year_of_death: 2007,
        demo__days_to_death: 253,
        demo__state: 'released',
        demo__created_datetime: null,
        demo__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
        diag__diagnosis_id: '4176108f-948d-5715-afbb-cc21f3cbfaf5',
        diag__ajcc_clinical_n: 'N3',
        diag__masaoka_stage: null,
        diag__ajcc_clinical_m: 'M0',
        diag__primary_diagnosis: 'Squamous cell carcinoma, NOS',
        diag__primary_gleason_grade: null,
        diag__year_of_diagnosis: 2007,
        diag__figo_stage: null,
        diag__progression_or_recurrence: 'not reported',
        diag__ajcc_pathologic_m: 'M0',
        diag__site_of_resection_or_biopsy: 'Larynx, NOS',
        diag__ajcc_staging_system_edition: '6th',
        diag__icd_10_code: 'C32.9',
        diag__age_at_diagnosis: 17635,
        diag__ajcc_clinical_t: 'T4a',
        diag__days_to_last_follow_up: null,
        diag__ajcc_pathologic_stage: 'Stage IVB',
        diag__tumor_grade: 'not reported',
        diag__last_known_disease_status: 'not reported',
        diag__ann_arbor_extranodal_involvement: null,
        diag__ajcc_clinical_stage: 'Stage IVB',
        diag__secondary_gleason_grade: null,
        diag__synchronous_malignancy: 'No',
        diag__morphology: '8070/3',
        diag__ajcc_pathologic_t: 'T4a',
        diag__igcccg_stage: null,
        diag__classification_of_tumor: 'not reported',
        diag__ann_arbor_clinical_stage: null,
        diag__ann_arbor_b_symptoms: null,
        diag__tumor_stage: 'stage ivb',
        diag__prior_treatment: 'No',
        diag__ajcc_pathologic_n: 'N3',
        diag__tissue_or_organ_of_origin: 'Larynx, NOS',
        diag__prior_malignancy: 'no',
        diag__state: 'released',
        diag__created_datetime: null,
        diag__updated_datetime: '2019-08-08T16:44:42.154844-05:00',
        exp__exposure_id: 'beef5b0a-0621-5abd-97bc-d0ef1261a94d',
        exp__height: null,
        exp__weight: null,
        exp__bmi: null,
        exp__years_smoked: null,
        exp__pack_years_smoked: 15,
        exp__cigarettes_per_day: 0.821917808219178,
        exp__alcohol_history: 'Yes',
        exp__state: 'released',
        exp__created_datetime: null,
        exp__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
        state: 'released',
        updated_datetime: '2019-08-06T14:25:25.511101-05:00',
        diagnoses: [
          {
            diag__diagnosis_id: '4176108f-948d-5715-afbb-cc21f3cbfaf5',
            diag__treat__treatment_id: 'e62a815e-6907-5bc7-acbc-932bc0a05b75',
            case_id: '291b069c-9dde-4e1e-8430-85146bc94338',
            diag__treat__treatment_type: 'Pharmaceutical Therapy, NOS',
            diag__treat__treatment_or_therapy: 'not reported',
            diag__treat__state: 'released',
            diag__treat__created_datetime: '2019-04-28T11:26:52.133657-05:00',
            diag__treat__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
          },
          {
            diag__diagnosis_id: '4176108f-948d-5715-afbb-cc21f3cbfaf5',
            diag__treat__treatment_id: 'f46facb0-9a93-5077-a9b5-b8f907404520',
            case_id: '291b069c-9dde-4e1e-8430-85146bc94338',
            diag__treat__treatment_type: 'Radiation Therapy, NOS',
            diag__treat__treatment_or_therapy: 'not reported',
            diag__treat__state: 'released',
            diag__treat__created_datetime: null,
            diag__treat__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
          },
        ],
        biospecimen: [
          {
            sample_barcode: 'TCGA-CN-5363-10A',
            sample_gdc_id: '591e99ec-46f9-442d-ac20-745dccc8a52b',
            case_barcode: 'TCGA-CN-5363',
            case_gdc_id: '291b069c-9dde-4e1e-8430-85146bc94338',
            sample_type: '10',
            sample_type_name: 'Blood Derived Normal',
            program_name: 'TCGA',
            project_short_name: 'TCGA-HNSC',
            batch_number: 54,
            bcr: "Nationwide Children's Hospital",
            days_to_collection: null,
            days_to_sample_procurement: 27,
            is_ffpe: 'NO',
            num_portions: 1,
            num_slides: 0,
            avg_percent_lymphocyte_infiltration: null,
            avg_percent_monocyte_infiltration: null,
            avg_percent_necrosis: null,
            avg_percent_neutrophil_infiltration: null,
            avg_percent_normal_cells: null,
            avg_percent_tumor_nuclei: null,
            max_percent_lymphocyte_infiltration: null,
            max_percent_monocyte_infiltration: null,
            max_percent_necrosis: null,
            max_percent_neutrophil_infiltration: null,
            max_percent_normal_cells: null,
            max_percent_stromal_cells: null,
            max_percent_tumor_cells: null,
            max_percent_tumor_nuclei: null,
            min_percent_lymphocyte_infiltration: null,
            min_percent_monocyte_infiltration: null,
            min_percent_necrosis: null,
            min_percent_neutrophil_infiltration: null,
            min_percent_normal_cells: null,
            min_percent_stromal_cells: null,
            min_percent_tumor_cells: null,
            min_percent_tumor_nuclei: null,
          },
          {
            sample_barcode: 'TCGA-CN-5363-01A',
            sample_gdc_id: '5e4e1e21-8016-4e27-8f72-2411714203e8',
            case_barcode: 'TCGA-CN-5363',
            case_gdc_id: '291b069c-9dde-4e1e-8430-85146bc94338',
            sample_type: '01',
            sample_type_name: 'Primary solid Tumor',
            program_name: 'TCGA',
            project_short_name: 'TCGA-HNSC',
            batch_number: 54,
            bcr: "Nationwide Children's Hospital",
            days_to_collection: null,
            days_to_sample_procurement: 3,
            is_ffpe: 'NO',
            num_portions: 1,
            num_slides: 2,
            avg_percent_lymphocyte_infiltration: null,
            avg_percent_monocyte_infiltration: null,
            avg_percent_necrosis: 0,
            avg_percent_neutrophil_infiltration: null,
            avg_percent_normal_cells: 0,
            avg_percent_tumor_nuclei: 70,
            max_percent_lymphocyte_infiltration: null,
            max_percent_monocyte_infiltration: null,
            max_percent_necrosis: null,
            max_percent_neutrophil_infiltration: null,
            max_percent_normal_cells: 0,
            max_percent_stromal_cells: 10,
            max_percent_tumor_cells: 90,
            max_percent_tumor_nuclei: 70,
            min_percent_lymphocyte_infiltration: null,
            min_percent_monocyte_infiltration: null,
            min_percent_necrosis: 0,
            min_percent_neutrophil_infiltration: null,
            min_percent_normal_cells: 0,
            min_percent_stromal_cells: 10,
            min_percent_tumor_cells: 90,
            min_percent_tumor_nuclei: 70,
          },
        ],
      },
    ]);
  });

  it('should getAllDiagnosis', async () => {
    const [rows] = await service.getAllDiagnosis();
    expect(rows).toEqual([
      {
        submitter_id: 'TCGA-CN-5363',
        case_id: '291b069c-9dde-4e1e-8430-85146bc94338',
        diag__treat__count: 2,
        primary_site: 'Larynx',
        disease_type: 'Squamous Cell Neoplasms',
        proj__name: 'Head and Neck Squamous Cell Carcinoma',
        proj__project_id: 'TCGA-HNSC',
        demo__demographic_id: '2611cb61-6d05-5286-b94a-ce6cac2ba37b',
        demo__gender: 'male',
        demo__race: 'black or african american',
        demo__ethnicity: 'not hispanic or latino',
        demo__vital_status: 'Dead',
        demo__days_to_birth: -17635,
        demo__year_of_birth: 1959,
        demo__age_at_index: 48,
        demo__year_of_death: 2007,
        demo__days_to_death: 253,
        demo__state: 'released',
        demo__created_datetime: null,
        demo__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
        diag__diagnosis_id: '4176108f-948d-5715-afbb-cc21f3cbfaf5',
        diag__ajcc_clinical_n: 'N3',
        diag__masaoka_stage: null,
        diag__ajcc_clinical_m: 'M0',
        diag__primary_diagnosis: 'Squamous cell carcinoma, NOS',
        diag__primary_gleason_grade: null,
        diag__year_of_diagnosis: 2007,
        diag__figo_stage: null,
        diag__progression_or_recurrence: 'not reported',
        diag__ajcc_pathologic_m: 'M0',
        diag__site_of_resection_or_biopsy: 'Larynx, NOS',
        diag__ajcc_staging_system_edition: '6th',
        diag__icd_10_code: 'C32.9',
        diag__age_at_diagnosis: 17635,
        diag__ajcc_clinical_t: 'T4a',
        diag__days_to_last_follow_up: null,
        diag__ajcc_pathologic_stage: 'Stage IVB',
        diag__tumor_grade: 'not reported',
        diag__last_known_disease_status: 'not reported',
        diag__ann_arbor_extranodal_involvement: null,
        diag__ajcc_clinical_stage: 'Stage IVB',
        diag__secondary_gleason_grade: null,
        diag__synchronous_malignancy: 'No',
        diag__morphology: '8070/3',
        diag__ajcc_pathologic_t: 'T4a',
        diag__igcccg_stage: null,
        diag__classification_of_tumor: 'not reported',
        diag__ann_arbor_clinical_stage: null,
        diag__ann_arbor_b_symptoms: null,
        diag__tumor_stage: 'stage ivb',
        diag__prior_treatment: 'No',
        diag__ajcc_pathologic_n: 'N3',
        diag__tissue_or_organ_of_origin: 'Larynx, NOS',
        diag__prior_malignancy: 'no',
        diag__state: 'released',
        diag__created_datetime: null,
        diag__updated_datetime: '2019-08-08T16:44:42.154844-05:00',
        exp__exposure_id: 'beef5b0a-0621-5abd-97bc-d0ef1261a94d',
        exp__height: null,
        exp__weight: null,
        exp__bmi: null,
        exp__years_smoked: null,
        exp__pack_years_smoked: 15,
        exp__cigarettes_per_day: 0.821917808219178,
        exp__alcohol_history: 'Yes',
        exp__state: 'released',
        exp__created_datetime: null,
        exp__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
        state: 'released',
        updated_datetime: '2019-08-06T14:25:25.511101-05:00',
        diag__diagnosis_id_1: '4176108f-948d-5715-afbb-cc21f3cbfaf5',
        diag__treat__treatment_id: 'f46facb0-9a93-5077-a9b5-b8f907404520',
        case_id_1: '291b069c-9dde-4e1e-8430-85146bc94338',
        diag__treat__treatment_type: 'Radiation Therapy, NOS',
        diag__treat__treatment_or_therapy: 'not reported',
        diag__treat__state: 'released',
        diag__treat__created_datetime: null,
        diag__treat__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
        sample_barcode: 'TCGA-CN-5363-01A',
        sample_gdc_id: '5e4e1e21-8016-4e27-8f72-2411714203e8',
        case_barcode: 'TCGA-CN-5363',
        case_gdc_id: '291b069c-9dde-4e1e-8430-85146bc94338',
        sample_type: '01',
        sample_type_name: 'Primary solid Tumor',
        program_name: 'TCGA',
        project_short_name: 'TCGA-HNSC',
        batch_number: 54,
        bcr: "Nationwide Children's Hospital",
        days_to_collection: null,
        days_to_sample_procurement: 3,
        is_ffpe: 'NO',
        num_portions: 1,
        num_slides: 2,
        avg_percent_lymphocyte_infiltration: null,
        avg_percent_monocyte_infiltration: null,
        avg_percent_necrosis: 0,
        avg_percent_neutrophil_infiltration: null,
        avg_percent_normal_cells: 0,
        avg_percent_stromal_cells: 10,
        avg_percent_tumor_cells: 90,
        avg_percent_tumor_nuclei: 70,
        max_percent_lymphocyte_infiltration: null,
        max_percent_monocyte_infiltration: null,
        max_percent_necrosis: 0,
        max_percent_neutrophil_infiltration: null,
        max_percent_normal_cells: 0,
        max_percent_stromal_cells: 10,
        max_percent_tumor_cells: 90,
        max_percent_tumor_nuclei: 70,
        min_percent_lymphocyte_infiltration: null,
        min_percent_monocyte_infiltration: null,
        min_percent_necrosis: 0,
        min_percent_neutrophil_infiltration: null,
        min_percent_normal_cells: 0,
        min_percent_stromal_cells: 10,
        min_percent_tumor_cells: 90,
        min_percent_tumor_nuclei: 70,
      },
      {
        submitter_id: 'TCGA-CN-5363',
        case_id: '291b069c-9dde-4e1e-8430-85146bc94338',
        diag__treat__count: 2,
        primary_site: 'Larynx',
        disease_type: 'Squamous Cell Neoplasms',
        proj__name: 'Head and Neck Squamous Cell Carcinoma',
        proj__project_id: 'TCGA-HNSC',
        demo__demographic_id: '2611cb61-6d05-5286-b94a-ce6cac2ba37b',
        demo__gender: 'male',
        demo__race: 'black or african american',
        demo__ethnicity: 'not hispanic or latino',
        demo__vital_status: 'Dead',
        demo__days_to_birth: -17635,
        demo__year_of_birth: 1959,
        demo__age_at_index: 48,
        demo__year_of_death: 2007,
        demo__days_to_death: 253,
        demo__state: 'released',
        demo__created_datetime: null,
        demo__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
        diag__diagnosis_id: '4176108f-948d-5715-afbb-cc21f3cbfaf5',
        diag__ajcc_clinical_n: 'N3',
        diag__masaoka_stage: null,
        diag__ajcc_clinical_m: 'M0',
        diag__primary_diagnosis: 'Squamous cell carcinoma, NOS',
        diag__primary_gleason_grade: null,
        diag__year_of_diagnosis: 2007,
        diag__figo_stage: null,
        diag__progression_or_recurrence: 'not reported',
        diag__ajcc_pathologic_m: 'M0',
        diag__site_of_resection_or_biopsy: 'Larynx, NOS',
        diag__ajcc_staging_system_edition: '6th',
        diag__icd_10_code: 'C32.9',
        diag__age_at_diagnosis: 17635,
        diag__ajcc_clinical_t: 'T4a',
        diag__days_to_last_follow_up: null,
        diag__ajcc_pathologic_stage: 'Stage IVB',
        diag__tumor_grade: 'not reported',
        diag__last_known_disease_status: 'not reported',
        diag__ann_arbor_extranodal_involvement: null,
        diag__ajcc_clinical_stage: 'Stage IVB',
        diag__secondary_gleason_grade: null,
        diag__synchronous_malignancy: 'No',
        diag__morphology: '8070/3',
        diag__ajcc_pathologic_t: 'T4a',
        diag__igcccg_stage: null,
        diag__classification_of_tumor: 'not reported',
        diag__ann_arbor_clinical_stage: null,
        diag__ann_arbor_b_symptoms: null,
        diag__tumor_stage: 'stage ivb',
        diag__prior_treatment: 'No',
        diag__ajcc_pathologic_n: 'N3',
        diag__tissue_or_organ_of_origin: 'Larynx, NOS',
        diag__prior_malignancy: 'no',
        diag__state: 'released',
        diag__created_datetime: null,
        diag__updated_datetime: '2019-08-08T16:44:42.154844-05:00',
        exp__exposure_id: 'beef5b0a-0621-5abd-97bc-d0ef1261a94d',
        exp__height: null,
        exp__weight: null,
        exp__bmi: null,
        exp__years_smoked: null,
        exp__pack_years_smoked: 15,
        exp__cigarettes_per_day: 0.821917808219178,
        exp__alcohol_history: 'Yes',
        exp__state: 'released',
        exp__created_datetime: null,
        exp__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
        state: 'released',
        updated_datetime: '2019-08-06T14:25:25.511101-05:00',
        diag__diagnosis_id_1: '4176108f-948d-5715-afbb-cc21f3cbfaf5',
        diag__treat__treatment_id: 'f46facb0-9a93-5077-a9b5-b8f907404520',
        case_id_1: '291b069c-9dde-4e1e-8430-85146bc94338',
        diag__treat__treatment_type: 'Radiation Therapy, NOS',
        diag__treat__treatment_or_therapy: 'not reported',
        diag__treat__state: 'released',
        diag__treat__created_datetime: null,
        diag__treat__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
        sample_barcode: 'TCGA-CN-5363-10A',
        sample_gdc_id: '591e99ec-46f9-442d-ac20-745dccc8a52b',
        case_barcode: 'TCGA-CN-5363',
        case_gdc_id: '291b069c-9dde-4e1e-8430-85146bc94338',
        sample_type: '10',
        sample_type_name: 'Blood Derived Normal',
        program_name: 'TCGA',
        project_short_name: 'TCGA-HNSC',
        batch_number: 54,
        bcr: "Nationwide Children's Hospital",
        days_to_collection: null,
        days_to_sample_procurement: 27,
        is_ffpe: 'NO',
        num_portions: 1,
        num_slides: 0,
        avg_percent_lymphocyte_infiltration: null,
        avg_percent_monocyte_infiltration: null,
        avg_percent_necrosis: null,
        avg_percent_neutrophil_infiltration: null,
        avg_percent_normal_cells: null,
        avg_percent_stromal_cells: null,
        avg_percent_tumor_cells: null,
        avg_percent_tumor_nuclei: null,
        max_percent_lymphocyte_infiltration: null,
        max_percent_monocyte_infiltration: null,
        max_percent_necrosis: null,
        max_percent_neutrophil_infiltration: null,
        max_percent_normal_cells: null,
        max_percent_stromal_cells: null,
        max_percent_tumor_cells: null,
        max_percent_tumor_nuclei: null,
        min_percent_lymphocyte_infiltration: null,
        min_percent_monocyte_infiltration: null,
        min_percent_necrosis: null,
        min_percent_neutrophil_infiltration: null,
        min_percent_normal_cells: null,
        min_percent_stromal_cells: null,
        min_percent_tumor_cells: null,
        min_percent_tumor_nuclei: null,
      },
      {
        submitter_id: 'TCGA-CN-5363',
        case_id: '291b069c-9dde-4e1e-8430-85146bc94338',
        diag__treat__count: 2,
        primary_site: 'Larynx',
        disease_type: 'Squamous Cell Neoplasms',
        proj__name: 'Head and Neck Squamous Cell Carcinoma',
        proj__project_id: 'TCGA-HNSC',
        demo__demographic_id: '2611cb61-6d05-5286-b94a-ce6cac2ba37b',
        demo__gender: 'male',
        demo__race: 'black or african american',
        demo__ethnicity: 'not hispanic or latino',
        demo__vital_status: 'Dead',
        demo__days_to_birth: -17635,
        demo__year_of_birth: 1959,
        demo__age_at_index: 48,
        demo__year_of_death: 2007,
        demo__days_to_death: 253,
        demo__state: 'released',
        demo__created_datetime: null,
        demo__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
        diag__diagnosis_id: '4176108f-948d-5715-afbb-cc21f3cbfaf5',
        diag__ajcc_clinical_n: 'N3',
        diag__masaoka_stage: null,
        diag__ajcc_clinical_m: 'M0',
        diag__primary_diagnosis: 'Squamous cell carcinoma, NOS',
        diag__primary_gleason_grade: null,
        diag__year_of_diagnosis: 2007,
        diag__figo_stage: null,
        diag__progression_or_recurrence: 'not reported',
        diag__ajcc_pathologic_m: 'M0',
        diag__site_of_resection_or_biopsy: 'Larynx, NOS',
        diag__ajcc_staging_system_edition: '6th',
        diag__icd_10_code: 'C32.9',
        diag__age_at_diagnosis: 17635,
        diag__ajcc_clinical_t: 'T4a',
        diag__days_to_last_follow_up: null,
        diag__ajcc_pathologic_stage: 'Stage IVB',
        diag__tumor_grade: 'not reported',
        diag__last_known_disease_status: 'not reported',
        diag__ann_arbor_extranodal_involvement: null,
        diag__ajcc_clinical_stage: 'Stage IVB',
        diag__secondary_gleason_grade: null,
        diag__synchronous_malignancy: 'No',
        diag__morphology: '8070/3',
        diag__ajcc_pathologic_t: 'T4a',
        diag__igcccg_stage: null,
        diag__classification_of_tumor: 'not reported',
        diag__ann_arbor_clinical_stage: null,
        diag__ann_arbor_b_symptoms: null,
        diag__tumor_stage: 'stage ivb',
        diag__prior_treatment: 'No',
        diag__ajcc_pathologic_n: 'N3',
        diag__tissue_or_organ_of_origin: 'Larynx, NOS',
        diag__prior_malignancy: 'no',
        diag__state: 'released',
        diag__created_datetime: null,
        diag__updated_datetime: '2019-08-08T16:44:42.154844-05:00',
        exp__exposure_id: 'beef5b0a-0621-5abd-97bc-d0ef1261a94d',
        exp__height: null,
        exp__weight: null,
        exp__bmi: null,
        exp__years_smoked: null,
        exp__pack_years_smoked: 15,
        exp__cigarettes_per_day: 0.821917808219178,
        exp__alcohol_history: 'Yes',
        exp__state: 'released',
        exp__created_datetime: null,
        exp__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
        state: 'released',
        updated_datetime: '2019-08-06T14:25:25.511101-05:00',
        diag__diagnosis_id_1: '4176108f-948d-5715-afbb-cc21f3cbfaf5',
        diag__treat__treatment_id: 'e62a815e-6907-5bc7-acbc-932bc0a05b75',
        case_id_1: '291b069c-9dde-4e1e-8430-85146bc94338',
        diag__treat__treatment_type: 'Pharmaceutical Therapy, NOS',
        diag__treat__treatment_or_therapy: 'not reported',
        diag__treat__state: 'released',
        diag__treat__created_datetime: '2019-04-28T11:26:52.133657-05:00',
        diag__treat__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
        sample_barcode: 'TCGA-CN-5363-01A',
        sample_gdc_id: '5e4e1e21-8016-4e27-8f72-2411714203e8',
        case_barcode: 'TCGA-CN-5363',
        case_gdc_id: '291b069c-9dde-4e1e-8430-85146bc94338',
        sample_type: '01',
        sample_type_name: 'Primary solid Tumor',
        program_name: 'TCGA',
        project_short_name: 'TCGA-HNSC',
        batch_number: 54,
        bcr: "Nationwide Children's Hospital",
        days_to_collection: null,
        days_to_sample_procurement: 3,
        is_ffpe: 'NO',
        num_portions: 1,
        num_slides: 2,
        avg_percent_lymphocyte_infiltration: null,
        avg_percent_monocyte_infiltration: null,
        avg_percent_necrosis: 0,
        avg_percent_neutrophil_infiltration: null,
        avg_percent_normal_cells: 0,
        avg_percent_stromal_cells: 10,
        avg_percent_tumor_cells: 90,
        avg_percent_tumor_nuclei: 70,
        max_percent_lymphocyte_infiltration: null,
        max_percent_monocyte_infiltration: null,
        max_percent_necrosis: 0,
        max_percent_neutrophil_infiltration: null,
        max_percent_normal_cells: 0,
        max_percent_stromal_cells: 10,
        max_percent_tumor_cells: 90,
        max_percent_tumor_nuclei: 70,
        min_percent_lymphocyte_infiltration: null,
        min_percent_monocyte_infiltration: null,
        min_percent_necrosis: 0,
        min_percent_neutrophil_infiltration: null,
        min_percent_normal_cells: 0,
        min_percent_stromal_cells: 10,
        min_percent_tumor_cells: 90,
        min_percent_tumor_nuclei: 70,
      },
      {
        submitter_id: 'TCGA-CN-5363',
        case_id: '291b069c-9dde-4e1e-8430-85146bc94338',
        diag__treat__count: 2,
        primary_site: 'Larynx',
        disease_type: 'Squamous Cell Neoplasms',
        proj__name: 'Head and Neck Squamous Cell Carcinoma',
        proj__project_id: 'TCGA-HNSC',
        demo__demographic_id: '2611cb61-6d05-5286-b94a-ce6cac2ba37b',
        demo__gender: 'male',
        demo__race: 'black or african american',
        demo__ethnicity: 'not hispanic or latino',
        demo__vital_status: 'Dead',
        demo__days_to_birth: -17635,
        demo__year_of_birth: 1959,
        demo__age_at_index: 48,
        demo__year_of_death: 2007,
        demo__days_to_death: 253,
        demo__state: 'released',
        demo__created_datetime: null,
        demo__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
        diag__diagnosis_id: '4176108f-948d-5715-afbb-cc21f3cbfaf5',
        diag__ajcc_clinical_n: 'N3',
        diag__masaoka_stage: null,
        diag__ajcc_clinical_m: 'M0',
        diag__primary_diagnosis: 'Squamous cell carcinoma, NOS',
        diag__primary_gleason_grade: null,
        diag__year_of_diagnosis: 2007,
        diag__figo_stage: null,
        diag__progression_or_recurrence: 'not reported',
        diag__ajcc_pathologic_m: 'M0',
        diag__site_of_resection_or_biopsy: 'Larynx, NOS',
        diag__ajcc_staging_system_edition: '6th',
        diag__icd_10_code: 'C32.9',
        diag__age_at_diagnosis: 17635,
        diag__ajcc_clinical_t: 'T4a',
        diag__days_to_last_follow_up: null,
        diag__ajcc_pathologic_stage: 'Stage IVB',
        diag__tumor_grade: 'not reported',
        diag__last_known_disease_status: 'not reported',
        diag__ann_arbor_extranodal_involvement: null,
        diag__ajcc_clinical_stage: 'Stage IVB',
        diag__secondary_gleason_grade: null,
        diag__synchronous_malignancy: 'No',
        diag__morphology: '8070/3',
        diag__ajcc_pathologic_t: 'T4a',
        diag__igcccg_stage: null,
        diag__classification_of_tumor: 'not reported',
        diag__ann_arbor_clinical_stage: null,
        diag__ann_arbor_b_symptoms: null,
        diag__tumor_stage: 'stage ivb',
        diag__prior_treatment: 'No',
        diag__ajcc_pathologic_n: 'N3',
        diag__tissue_or_organ_of_origin: 'Larynx, NOS',
        diag__prior_malignancy: 'no',
        diag__state: 'released',
        diag__created_datetime: null,
        diag__updated_datetime: '2019-08-08T16:44:42.154844-05:00',
        exp__exposure_id: 'beef5b0a-0621-5abd-97bc-d0ef1261a94d',
        exp__height: null,
        exp__weight: null,
        exp__bmi: null,
        exp__years_smoked: null,
        exp__pack_years_smoked: 15,
        exp__cigarettes_per_day: 0.821917808219178,
        exp__alcohol_history: 'Yes',
        exp__state: 'released',
        exp__created_datetime: null,
        exp__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
        state: 'released',
        updated_datetime: '2019-08-06T14:25:25.511101-05:00',
        diag__diagnosis_id_1: '4176108f-948d-5715-afbb-cc21f3cbfaf5',
        diag__treat__treatment_id: 'e62a815e-6907-5bc7-acbc-932bc0a05b75',
        case_id_1: '291b069c-9dde-4e1e-8430-85146bc94338',
        diag__treat__treatment_type: 'Pharmaceutical Therapy, NOS',
        diag__treat__treatment_or_therapy: 'not reported',
        diag__treat__state: 'released',
        diag__treat__created_datetime: '2019-04-28T11:26:52.133657-05:00',
        diag__treat__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
        sample_barcode: 'TCGA-CN-5363-10A',
        sample_gdc_id: '591e99ec-46f9-442d-ac20-745dccc8a52b',
        case_barcode: 'TCGA-CN-5363',
        case_gdc_id: '291b069c-9dde-4e1e-8430-85146bc94338',
        sample_type: '10',
        sample_type_name: 'Blood Derived Normal',
        program_name: 'TCGA',
        project_short_name: 'TCGA-HNSC',
        batch_number: 54,
        bcr: "Nationwide Children's Hospital",
        days_to_collection: null,
        days_to_sample_procurement: 27,
        is_ffpe: 'NO',
        num_portions: 1,
        num_slides: 0,
        avg_percent_lymphocyte_infiltration: null,
        avg_percent_monocyte_infiltration: null,
        avg_percent_necrosis: null,
        avg_percent_neutrophil_infiltration: null,
        avg_percent_normal_cells: null,
        avg_percent_stromal_cells: null,
        avg_percent_tumor_cells: null,
        avg_percent_tumor_nuclei: null,
        max_percent_lymphocyte_infiltration: null,
        max_percent_monocyte_infiltration: null,
        max_percent_necrosis: null,
        max_percent_neutrophil_infiltration: null,
        max_percent_normal_cells: null,
        max_percent_stromal_cells: null,
        max_percent_tumor_cells: null,
        max_percent_tumor_nuclei: null,
        min_percent_lymphocyte_infiltration: null,
        min_percent_monocyte_infiltration: null,
        min_percent_necrosis: null,
        min_percent_neutrophil_infiltration: null,
        min_percent_normal_cells: null,
        min_percent_stromal_cells: null,
        min_percent_tumor_cells: null,
        min_percent_tumor_nuclei: null,
      },
    ]);
  });

  it('should getDiagnosisById', async () => {
    const rows = await service.getDiagnosisById();
    expect(rows).toEqual({
      avg_percent_lymphocyte_infiltration: null,
      avg_percent_monocyte_infiltration: null,
      avg_percent_necrosis: 0,
      avg_percent_neutrophil_infiltration: null,
      avg_percent_normal_cells: 0,
      avg_percent_stromal_cells: 10,
      avg_percent_tumor_cells: 90,
      avg_percent_tumor_nuclei: 70,
      batch_number: 54,
      bcr: "Nationwide Children's Hospital",
      case_barcode: 'TCGA-CN-5363',
      case_gdc_id: '291b069c-9dde-4e1e-8430-85146bc94338',
      case_id: '291b069c-9dde-4e1e-8430-85146bc94338',
      case_id_1: '291b069c-9dde-4e1e-8430-85146bc94338',
      days_to_collection: null,
      days_to_sample_procurement: 3,
      demo__age_at_index: 48,
      demo__created_datetime: null,
      demo__days_to_birth: -17635,
      demo__days_to_death: 253,
      demo__demographic_id: '2611cb61-6d05-5286-b94a-ce6cac2ba37b',
      demo__ethnicity: 'not hispanic or latino',
      demo__gender: 'male',
      demo__race: 'black or african american',
      demo__state: 'released',
      demo__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
      demo__vital_status: 'Dead',
      demo__year_of_birth: 1959,
      demo__year_of_death: 2007,
      diag__age_at_diagnosis: 17635,
      diag__ajcc_clinical_m: 'M0',
      diag__ajcc_clinical_n: 'N3',
      diag__ajcc_clinical_stage: 'Stage IVB',
      diag__ajcc_clinical_t: 'T4a',
      diag__ajcc_pathologic_m: 'M0',
      diag__ajcc_pathologic_n: 'N3',
      diag__ajcc_pathologic_stage: 'Stage IVB',
      diag__ajcc_pathologic_t: 'T4a',
      diag__ajcc_staging_system_edition: '6th',
      diag__ann_arbor_b_symptoms: null,
      diag__ann_arbor_clinical_stage: null,
      diag__ann_arbor_extranodal_involvement: null,
      diag__classification_of_tumor: 'not reported',
      diag__created_datetime: null,
      diag__days_to_last_follow_up: null,
      diag__diagnosis_id: '4176108f-948d-5715-afbb-cc21f3cbfaf5',
      diag__diagnosis_id_1: '4176108f-948d-5715-afbb-cc21f3cbfaf5',
      diag__figo_stage: null,
      diag__icd_10_code: 'C32.9',
      diag__igcccg_stage: null,
      diag__last_known_disease_status: 'not reported',
      diag__masaoka_stage: null,
      diag__morphology: '8070/3',
      diag__primary_diagnosis: 'Squamous cell carcinoma, NOS',
      diag__primary_gleason_grade: null,
      diag__prior_malignancy: 'no',
      diag__prior_treatment: 'No',
      diag__progression_or_recurrence: 'not reported',
      diag__secondary_gleason_grade: null,
      diag__site_of_resection_or_biopsy: 'Larynx, NOS',
      diag__state: 'released',
      diag__synchronous_malignancy: 'No',
      diag__tissue_or_organ_of_origin: 'Larynx, NOS',
      diag__treat__count: 2,
      diag__treat__created_datetime: null,
      diag__treat__state: 'released',
      diag__treat__treatment_id: 'f46facb0-9a93-5077-a9b5-b8f907404520',
      diag__treat__treatment_or_therapy: 'not reported',
      diag__treat__treatment_type: 'Radiation Therapy, NOS',
      diag__treat__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
      diag__tumor_grade: 'not reported',
      diag__tumor_stage: 'stage ivb',
      diag__updated_datetime: '2019-08-08T16:44:42.154844-05:00',
      diag__year_of_diagnosis: 2007,
      disease_type: 'Squamous Cell Neoplasms',
      exp__alcohol_history: 'Yes',
      exp__bmi: null,
      exp__cigarettes_per_day: 0.821917808219178,
      exp__created_datetime: null,
      exp__exposure_id: 'beef5b0a-0621-5abd-97bc-d0ef1261a94d',
      exp__height: null,
      exp__pack_years_smoked: 15,
      exp__state: 'released',
      exp__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
      exp__weight: null,
      exp__years_smoked: null,
      is_ffpe: 'NO',
      max_percent_lymphocyte_infiltration: null,
      max_percent_monocyte_infiltration: null,
      max_percent_necrosis: 0,
      max_percent_neutrophil_infiltration: null,
      max_percent_normal_cells: 0,
      max_percent_stromal_cells: 10,
      max_percent_tumor_cells: 90,
      max_percent_tumor_nuclei: 70,
      min_percent_lymphocyte_infiltration: null,
      min_percent_monocyte_infiltration: null,
      min_percent_necrosis: 0,
      min_percent_neutrophil_infiltration: null,
      min_percent_normal_cells: 0,
      min_percent_stromal_cells: 10,
      min_percent_tumor_cells: 90,
      min_percent_tumor_nuclei: 70,
      num_portions: 1,
      num_slides: 2,
      primary_site: 'Larynx',
      program_name: 'TCGA',
      proj__name: 'Head and Neck Squamous Cell Carcinoma',
      proj__project_id: 'TCGA-HNSC',
      project_short_name: 'TCGA-HNSC',
      sample_barcode: 'TCGA-CN-5363-01A',
      sample_gdc_id: '5e4e1e21-8016-4e27-8f72-2411714203e8',
      sample_type: '01',
      sample_type_name: 'Primary solid Tumor',
      state: 'released',
      submitter_id: 'TCGA-CN-5363',
      updated_datetime: '2019-08-06T14:25:25.511101-05:00',
    });
  });

  it('should getAllBiospecimen', async () => {
    const [rows] = await service.getAllBiospecimen();
    expect(rows).toEqual(tcgaResults);
  });

  it('should getBiospecimenById', async () => {
    const rows = await service.getBiospecimenById();
    expect(rows).toEqual({
      submitter_id: 'TCGA-CN-5363',
      case_id: '291b069c-9dde-4e1e-8430-85146bc94338',
      diag__treat__count: 2,
      primary_site: 'Larynx',
      disease_type: 'Squamous Cell Neoplasms',
      proj__name: 'Head and Neck Squamous Cell Carcinoma',
      proj__project_id: 'TCGA-HNSC',
      demo__demographic_id: '2611cb61-6d05-5286-b94a-ce6cac2ba37b',
      demo__gender: 'male',
      demo__race: 'black or african american',
      demo__ethnicity: 'not hispanic or latino',
      demo__vital_status: 'Dead',
      demo__days_to_birth: -17635,
      demo__year_of_birth: 1959,
      demo__age_at_index: 48,
      demo__year_of_death: 2007,
      demo__days_to_death: 253,
      demo__state: 'released',
      demo__created_datetime: null,
      demo__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
      diag__diagnosis_id: '4176108f-948d-5715-afbb-cc21f3cbfaf5',
      diag__ajcc_clinical_n: 'N3',
      diag__masaoka_stage: null,
      diag__ajcc_clinical_m: 'M0',
      diag__primary_diagnosis: 'Squamous cell carcinoma, NOS',
      diag__primary_gleason_grade: null,
      diag__year_of_diagnosis: 2007,
      diag__figo_stage: null,
      diag__progression_or_recurrence: 'not reported',
      diag__ajcc_pathologic_m: 'M0',
      diag__site_of_resection_or_biopsy: 'Larynx, NOS',
      diag__ajcc_staging_system_edition: '6th',
      diag__icd_10_code: 'C32.9',
      diag__age_at_diagnosis: 17635,
      diag__ajcc_clinical_t: 'T4a',
      diag__days_to_last_follow_up: null,
      diag__ajcc_pathologic_stage: 'Stage IVB',
      diag__tumor_grade: 'not reported',
      diag__last_known_disease_status: 'not reported',
      diag__ann_arbor_extranodal_involvement: null,
      diag__ajcc_clinical_stage: 'Stage IVB',
      diag__secondary_gleason_grade: null,
      diag__synchronous_malignancy: 'No',
      diag__morphology: '8070/3',
      diag__ajcc_pathologic_t: 'T4a',
      diag__igcccg_stage: null,
      diag__classification_of_tumor: 'not reported',
      diag__ann_arbor_clinical_stage: null,
      diag__ann_arbor_b_symptoms: null,
      diag__tumor_stage: 'stage ivb',
      diag__prior_treatment: 'No',
      diag__ajcc_pathologic_n: 'N3',
      diag__tissue_or_organ_of_origin: 'Larynx, NOS',
      diag__prior_malignancy: 'no',
      diag__state: 'released',
      diag__created_datetime: null,
      diag__updated_datetime: '2019-08-08T16:44:42.154844-05:00',
      exp__exposure_id: 'beef5b0a-0621-5abd-97bc-d0ef1261a94d',
      exp__height: null,
      exp__weight: null,
      exp__bmi: null,
      exp__years_smoked: null,
      exp__pack_years_smoked: 15,
      exp__cigarettes_per_day: 0.821917808219178,
      exp__alcohol_history: 'Yes',
      exp__state: 'released',
      exp__created_datetime: null,
      exp__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
      state: 'released',
      updated_datetime: '2019-08-06T14:25:25.511101-05:00',
      diag__diagnosis_id_1: '4176108f-948d-5715-afbb-cc21f3cbfaf5',
      diag__treat__treatment_id: 'f46facb0-9a93-5077-a9b5-b8f907404520',
      case_id_1: '291b069c-9dde-4e1e-8430-85146bc94338',
      diag__treat__treatment_type: 'Radiation Therapy, NOS',
      diag__treat__treatment_or_therapy: 'not reported',
      diag__treat__state: 'released',
      diag__treat__created_datetime: null,
      diag__treat__updated_datetime: '2019-07-31T18:43:25.167078-05:00',
      sample_barcode: 'TCGA-CN-5363-01A',
      sample_gdc_id: '5e4e1e21-8016-4e27-8f72-2411714203e8',
      case_barcode: 'TCGA-CN-5363',
      case_gdc_id: '291b069c-9dde-4e1e-8430-85146bc94338',
      sample_type: '01',
      sample_type_name: 'Primary solid Tumor',
      program_name: 'TCGA',
      project_short_name: 'TCGA-HNSC',
      batch_number: 54,
      bcr: "Nationwide Children's Hospital",
      days_to_collection: null,
      days_to_sample_procurement: 3,
      is_ffpe: 'NO',
      num_portions: 1,
      num_slides: 2,
      avg_percent_lymphocyte_infiltration: null,
      avg_percent_monocyte_infiltration: null,
      avg_percent_necrosis: 0,
      avg_percent_neutrophil_infiltration: null,
      avg_percent_normal_cells: 0,
      avg_percent_stromal_cells: 10,
      avg_percent_tumor_cells: 90,
      avg_percent_tumor_nuclei: 70,
      max_percent_lymphocyte_infiltration: null,
      max_percent_monocyte_infiltration: null,
      max_percent_necrosis: 0,
      max_percent_neutrophil_infiltration: null,
      max_percent_normal_cells: 0,
      max_percent_stromal_cells: 10,
      max_percent_tumor_cells: 90,
      max_percent_tumor_nuclei: 70,
      min_percent_lymphocyte_infiltration: null,
      min_percent_monocyte_infiltration: null,
      min_percent_necrosis: 0,
      min_percent_neutrophil_infiltration: null,
      min_percent_normal_cells: 0,
      min_percent_stromal_cells: 10,
      min_percent_tumor_cells: 90,
      min_percent_tumor_nuclei: 70,
    });
  });
});
