name: Viewer - Build and Deploy to GCP App Engine

on:
  release:
    types: [released]

jobs:
  run-tests:
    name: Build and Deploy to GCP App Engine
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: viewer

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install
        run: npm install

      - name: Generate env
        run: node ../scripts/create-env-file.js REACT_APP_CLIENT_ID=738532639593-8hg9uu5e9skh4i4thi7l76h8tdtlv2uu.apps.googleusercontent.com REACT_APP_SCOPE="openid profile" REACT_APP_ISS=https://fhir.dev.envs-terra.bio/4_0_0/ REACT_APP_REDIRECT_URI=https://broad-fhir-dev.ue.r.appspot.com REACT_APP_CLIENT_SECRET=AITn5oeSt2vpqTD0a3BGzz9Q

      - name: Run lint
        run: npm run lint

      - name: Build app
        run: npm run build

      - name: Deploy to GCP App Engine
        run: gcloud -q app deploy
