name: Viewer - Build and Deploy to GCP App Engine

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    name: Build and Deploy to GCP App Engine
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: viewer

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install
        run: npm Install

      - name: Build app
        run: npm run build

      - name: Deploy to GCP App Engine
        run: gcloud -q app deploy