name: Viewer - Build and Deploy to GCP App Engine

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    name: Build and Deploy to GCP App Engine
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Use gcloud CLI
        run: pwd && ls
