name: Build and Push to GCR

on:
  push:

# Environment variables available to all jobs and steps in this workflow
#  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
#  GKE_KEY: ${{ secrets.GKE_KEY }}
env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  IMAGE: fhir
  ORGANIZATION: broad
  REGISTRY_HOSTNAME: gcr.io

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_key: ${{ secrets.GCR_KEY }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker

      # Build the Docker image
      - name: Build
        run: |
          export TAG=`echo $GITHUB_SHA | cut -c1-6`
          echo $TAG
          docker build -t "$REGISTRY_HOSTNAME"/"$ORGANIZATION"/"$IMAGE":"$TAG" .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          export TAG=`echo $GITHUB_SHA | cut -c1-6`
          echo $TAG
          docker push "$REGISTRY_HOSTNAME"/"$ORGANIZATION"/"$IMAGE":"$TAG"
          docker tag "$REGISTRY_HOSTNAME"/"$ORGANIZATION"/"$IMAGE":"$TAG" "$REGISTRY_HOSTNAME"/"$ORGANIZATION"/"$IMAGE":latest
          docker push "$REGISTRY_HOSTNAME"/"$ORGANIZATION"/"$IMAGE":latest
