name: Test

on:
  push:
    branches:
      - master

env:
  NODE_ENV: TEST

jobs:
  test:
    name: Run Jest tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          NODE_ENV: TEST
      - name: Install
        run: npm install
      - name: Test
        run: npm test
